# train and val data as 1) directory: path/images/, 2) file: path/images.txt, or 3) list: [path1/images/, path2/images/]
train: data/
val: data/

# number of classes
nc: 7

# class names
names: ['condition','molecule','electrophile','reagent','product','yield','reaction']